// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemasTarefas.Data;

#nullable disable

namespace SistemasTarefas.Migrations
{
    [DbContext(typeof(UsuariosDbContext))]
    [Migration("20231001144630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemasTarefas.Models.Tarefas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("SistemasTarefas.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("NumberPhone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemasTarefas.Models.UsuariosTarefas", b =>
                {
                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.Property<int>("TarefasId")
                        .HasColumnType("integer");

                    b.HasKey("UsuariosId", "TarefasId");

                    b.HasIndex("TarefasId");

                    b.ToTable("UsuariosTarefas");
                });

            modelBuilder.Entity("SistemasTarefas.Models.Tarefas", b =>
                {
                    b.HasOne("SistemasTarefas.Models.Usuarios", "Usuarios")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemasTarefas.Models.UsuariosTarefas", b =>
                {
                    b.HasOne("SistemasTarefas.Models.Tarefas", "Tarefas")
                        .WithMany()
                        .HasForeignKey("TarefasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemasTarefas.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemasTarefas.Models.Usuarios", b =>
                {
                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
